"mcp.handle_api_key":
  fn: mcp_api_key
  type: tool
  summary: Save provided Google Gemini API Key in .env file
  description: Responds true if provided Google Gemini API Key is valid or raises error if its invalid.
  body:
    type: object
    required:
      - api_key
    properties:
      api_key:
        type: string
  
